name=LF_Alpha
version=1.0.0
author=EARTKEY
maintainer=EARTKEY <eartkey@gmail.com>
sentence=Comprehensive embedded library for LF Alpha devices by EARTKEY
paragraph=The LF_Alpha library provides a robust set of tools and functions to interface with LF Alpha devices, enabling developers to easily integrate these devices into their projects. It supports various functionalities including data acquisition, device configuration, and communication protocols.
category=Other
url=provide GitHub Link here
architectures=esp32
depends=Wire,SPI
includes=LF_Alpha.h